### ISSUE TITLE
For output arguments, don't return an object but instead take preallocated storage

### ISSUE THREAD

**Issue by mikolalysenko** [scijs/ndarray-ldl-factorization#2]
Reallocating storage for ndarrays is very expensive.  It is probably better to give users some control over this function for now.  To do this you could pass the output as arguments to the ldl routine, as is done in many of the ndarray-ops modules.

**Comment by Planeshifter** [comment]
Okay, sure. It's good to have a consistent interface, too, and the other modules also mutate input arguments. I have modified the code accordingly and will push the changes now.
