### ISSUE TITLE
Question about world,

### ISSUE THREAD

**Issue by lightning02** [scijs/ndarray-ldl-factorization#4]
Matierials and stuff of your mod will generate only in new chunks? Or even in old chunks of my world?

**Comment by rreusser** [comment]
Not sure what this means but due to the same issue showing up in:
- rwtema/extrautilities#695
- SleepyTrousers/EnderIO#2670
- Chisel-2/Chisel-2#378
- BuildCraft/BuildCraft#2915

I'm gonna consider this closable.
